// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFIh-wLJGn2SBcp8yT7_WDAAioou__NPI',
    appId: '1:255425572188:web:50b0b1eb83f532e7e76599',
    messagingSenderId: '255425572188',
    projectId: 'nexusbot-5edeb',
    authDomain: 'nexusbot-5edeb.firebaseapp.com',
    storageBucket: 'nexusbot-5edeb.firebasestorage.app',
    measurementId: 'G-V8N57NMQXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHeBlAbz5jM06IWK7Tg0zR60d8L-i018',
    appId: '1:255425572188:android:66e24800f5ebfd1ae76599',
    messagingSenderId: '255425572188',
    projectId: 'nexusbot-5edeb',
    storageBucket: 'nexusbot-5edeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzRy5CVameHJ8OG976abbwBPy74M6i6M',
    appId: '1:255425572188:ios:9b9958655237037de76599',
    messagingSenderId: '255425572188',
    projectId: 'nexusbot-5edeb',
    storageBucket: 'nexusbot-5edeb.firebasestorage.app',
    iosClientId:
        '255425572188-n7nvtd35sf60mbh6raf8jp1u1tfnussj.apps.googleusercontent.com',
    iosBundleId: 'com.hintekk.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzRy5CVameHJ8OG976abbwBPy74M6i6M',
    appId: '1:255425572188:ios:9b9958655237037de76599',
    messagingSenderId: '255425572188',
    projectId: 'nexusbot-5edeb',
    storageBucket: 'nexusbot-5edeb.firebasestorage.app',
    iosClientId:
        '255425572188-n7nvtd35sf60mbh6raf8jp1u1tfnussj.apps.googleusercontent.com',
    iosBundleId: 'com.hintekk.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFIh-wLJGn2SBcp8yT7_WDAAioou__NPI',
    appId: '1:255425572188:web:71c286595ef11899e76599',
    messagingSenderId: '255425572188',
    projectId: 'nexusbot-5edeb',
    authDomain: 'nexusbot-5edeb.firebaseapp.com',
    storageBucket: 'nexusbot-5edeb.firebasestorage.app',
    measurementId: 'G-63XL2J3L39',
  );
}
